# Generated by Django 4.0.4 on 2022-06-25 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
    ]
